---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: ai4cloudops-f7f10d9
#  name: ts-register-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: ts-register-service
#  template:
#    metadata:
#      namespace: ai4cloudops-f7f10d9
#      labels:
#        app: ts-register-service
#    spec:
#      imagePullSecrets:
#        - name: regcred
#      containers:
#      - name: ts-register-service
#        image: smqasim/ts-register-service:astraea
#        imagePullPolicy: IfNotPresent
#        resources:
#          requests:
#            cpu: 50m
#            memory: 100Mi
#          limits:
#            cpu: 200m
#            memory: 500Mi
#
#        ports:
#        - containerPort: 12344

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-route-plan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-route-plan-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-route-plan-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-route-plan-service
        image: smqasim/ts-route-plan-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 14578

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-route-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-route-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-route-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-route-service
        image: smqasim/ts-route-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 11178

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-seat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ts-seat-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-seat-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-seat-service
        image: smqasim/ts-seat-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 18898

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-security-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-security-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-security-service
        image: smqasim/ts-security-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 11188

---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: ai4cloudops-f7f10d9
#  name: ts-sso-service
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: ts-sso-service
#  template:
#    metadata:
#      namespace: ai4cloudops-f7f10d9
#      labels:
#        app: ts-sso-service
#    spec:
#      containers:
#      - name: ts-sso-service
#        image: smqasim/ts-sso-service:astraea
#        imagePullPolicy: IfNotPresent
#        resources:
#          requests:
#            cpu: 50m
#            memory: 100Mi
#          limits:
#            cpu: 200m
#            memory: 500Mi
#
#        ports:
#        - containerPort: 12349

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-station-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-station-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-station-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-station-service
        image: smqasim/ts-station-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 12345

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-ticket-office-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-ticket-office-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-ticket-office-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-ticket-office-service
        image: smqasim/ts-ticket-office-service:astraea
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 16108

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-ticketinfo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-ticketinfo-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-ticketinfo-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-ticketinfo-service
        image: smqasim/ts-ticketinfo-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 15681

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-train-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-train-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-train-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-train-service
        image: smqasim/ts-train-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 14567

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-travel2-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ts-travel2-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-travel2-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-travel2-service
        image: smqasim/ts-travel2-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 16346

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-travel-plan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-travel-plan-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-travel-plan-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-travel-plan-service
        image: smqasim/ts-travel-plan-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 14322

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-travel-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-travel-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-travel-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-travel-service
        image: smqasim/ts-travel-service:astraea
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 12346

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-verification-code-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-verification-code-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-verification-code-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-verification-code-service
        image: smqasim/ts-verification-code-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 15678

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-voucher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-voucher-service
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-voucher-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-voucher-service
        image: smqasim/ts-voucher-service:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi

        ports:
        - containerPort: 16101


---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-user-service
  template:
    metadata:
      labels:
        app: ts-user-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-user-service
        image: smqasim/ts-user-service:astraea
        imagePullPolicy: Always
        ports:
        - containerPort: 12342
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12342
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-auth-service
  template:
    metadata:
      labels:
        app: ts-auth-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ts-auth-service
        image: smqasim/ts-auth-service:astraea
        imagePullPolicy: Always
        ports:
        - containerPort: 12340
        resources:
          requests:
            cpu: 50m
            memory: 160Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 12340
          initialDelaySeconds: 160
          periodSeconds: 10
          timeoutSeconds: 5
---


---
#apiVersion: v1
#kind: Service
#metadata:
#  namespace: ai4cloudops-f7f10d9
#  name: ts-register-service
#spec:
#  ports:
#    - name: http
#      port: 12344
#  selector:
#   app: ts-register-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-route-plan-service
spec:
  ports:
    - name: http
      port: 14578
  selector:
   app: ts-route-plan-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-route-service
spec:
  ports:
    - name: http
      port: 11178
  selector:
   app: ts-route-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-seat-service
spec:
  ports:
    - name: http
      port: 18898
  selector:
   app: ts-seat-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-security-service
spec:
  ports:
    - name: http
      port: 11188
  selector:
   app: ts-security-service

---

#apiVersion: v1
#kind: Service
#metadata:
#  namespace: ai4cloudops-f7f10d9
#  name: ts-sso-service
#spec:
#  ports:
#    - name: http
#      port: 12349
#  selector:
#   app: ts-sso-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-station-service
spec:
  ports:
    - name: http
      port: 12345
  selector:
   app: ts-station-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-ticket-office-service
spec:
  ports:
    - name: http
      port: 16108
  selector:
   app: ts-ticket-office-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-ticketinfo-service
spec:
  ports:
    - name: http
      port: 15681
  selector:
   app: ts-ticketinfo-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-train-service
spec:
  ports:
    - name: http
      port: 14567
  selector:
   app: ts-train-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-travel2-service
spec:
  ports:
    - name: http
      port: 16346
  selector:
   app: ts-travel2-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-travel-plan-service
spec:
  ports:
    - name: http
      port: 14322
  selector:
   app: ts-travel-plan-service

---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-travel-service
spec:
  ports:
    - name: http
      port: 12346
  selector:
   app: ts-travel-service


---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-verification-code-service
spec:
  ports:
    - name: http
      port: 15678
  selector:
   app: ts-verification-code-service


---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-voucher-service
spec:
  ports:
    - name: http
      port: 16101
  selector:
   app: ts-voucher-service

---
apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-user-service
spec:
  ports:
    - name: http
      port: 12342
  selector:
   app: ts-user-service

---
---

apiVersion: v1
kind: Service
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-auth-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 12340
  selector:
   app: ts-auth-service

---
