apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ai4cloudops-f7f10d9
  name: ts-ui-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-ui-dashboard
  template:
    metadata:
      namespace: ai4cloudops-f7f10d9
      labels:
        app: ts-ui-dashboard
    spec:
      containers:
      - name: ts-ui-dashboard
        image: smqasim/ts-ui-dashboard:astraea
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: ts-ui-dashboard
  namespace: ai4cloudops-f7f10d9
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30099
  selector:
   app: ts-ui-dashboard
---
